use std::{collections::HashSet, fs};

use crate::UMA_NAME_FILE;

pub fn read_uma_names() -> HashSet<String> {
    fs::read_to_string(UMA_NAME_FILE)
        .unwrap_or("".to_string())
        .lines()
        .map(|x| x.to_string())
        .collect::<HashSet<String>>()
}

// The list itself was made by AI, colours hand-picked. Some umas might be missing.
pub fn uma_fill_color(name: &str) -> String {
    match name {
        // "Admire Groove" => true,
        "Admire Vega" => "#608CCE",
        "Agnes Digital" => "#E29B98",
        "Agnes Tachyon" => "#DDCA89",
        "Air Groove" => "#836DAA",
        // "Air Messiah" => true,
        // "Air Shakur" => true,
        // "Almond Eye" => true,
        // "Aston Machan" => true,
        // "Bamboo Memory" => true,
        // "Believe" => true,
        // "Biko Pegasus" => true,
        "Biwa Hayahide" => "#D4B6B5",
        // "Blast Onepiece" => true,
        // "Bubble Gum Fellow" => true,
        // "Buena Vista" => true,
        // "Calstone Light O" => true,
        // "Cesario" => true,
        // "Cheval Grand" => true,
        // "Chrono Genesis" => true,
        // "Copano Rickey" => true,
        // "Curren Bouquetd'or" => true,
        "Curren Chan" => "#FFB7F0",
        // "Daiichi Ruby" => true,
        // "Daitaku Helios" => true,
        "Daiwa Scarlet" => "##4C65CB",
        // "Dantsu Flame" => true,
        // "Daring Heart" => true,
        // "Daring Tact" => true,
        // "Darley Arabian" => true,
        // "Dream Journey" => true,
        // "Duramente" => true,
        // "Durandal" => true,
        "Eishin Flash" => "#4F5167",
        "El Condor Pasa" => "#D72A13",
        // "Espoir City" => true,
        // "Fenomeno" => true,
        "Fine Motion" => "#43A26B",
        "Fuji Kiseki" => "#777B82",
        // "Furioso" => true,
        // "Fusaichi Pandora" => true,
        // "Gentildonna" => true,
        "Gold City" => "#F5C188",
        "Gold Ship" => "#E62D3F",
        // "Gran Alegria" => true,
        "Grass Wonder" => "#6279C1",
        // "Haiseiko" => true,
        // "Happy Meek" => true,
        "Haru Urara" => "#FEAEB0",
        "Hishi Akebono" => "#135FBE",
        "Hishi Amazon" => "#EFB371",
        // "Hishi Miracle" => true,
        // "Hokko Tarumae" => true,
        // "Ikuno Dictus" => true,
        // "Inari One" => true,
        // "Ines Fujin" => true,
        // "Jungle Pocket" => true,
        // "K.S. Miracle" => true,
        // "Katsuragi Ace" => true,
        "Kawakami Princess" => "#F1619F",
        "King Halo" => "#6279C1",
        "Kitasan Black" => "#D75B69",
        // "Loves Only You" => true,
        // "Lucky Lilac" => true,
        "Manhattan Cafe" => "#F2CD5B",
        "Maruzensky" => "#E04F27",
        // "Marvelous Sunday" => true,
        "Matikanefukukitaru" => "#ECC955",
        // "Matikanetannhauser" => true,
        "Mayano Top Gun" => "#FE9757",
        "Meisho Doto" => "#BE7055",
        // "Mejiro Ardan" => true,
        // "Mejiro Bright" => true,
        "Mejiro Dober" => "#6EBEC4",
        "Mejiro McQueen" => "#C0AEE0",
        // "Mejiro Palmer" => true,
        // "Mejiro Ramonu" => true,
        "Mejiro Ryan" => "#63BABC",
        "Mihono Bourbon" => "#FF5FFF",
        // "Mr. C.B." => true,
        // "Nakayama Festa" => true,
        "Narita Brian" => "#F3AE80",
        "Narita Taishin" => "#FCA0B9",
        // "Narita Top Road" => true,
        // "Neo Universe" => true,
        "Nice Nature" => "#B35B54",
        // "Nishino Flower" => true,
        // "No Reason" => true,
        // "North Flight" => true,
        "Oguri Cap" => "#D9D7DA",
        // "Orfevre" => true,
        "Rice Shower" => "#5A5182",
        // "Royce and Royce" => true,
        "Sakura Bakushin O" => "#FF78A7",
        // "Sakura Chitose O" => true,
        "Sakura Chiyono O" => "#FF9DBA",
        // "Sakura Laurel" => true,
        // "Satono Crown" => true,
        "Satono Diamond" => "#8DB087",
        // "Seeking the Pearl" => true,
        "Seiun Sky" => "#adcd91",
        // "Shinko Windy" => true,
        "Silence Suzuka" => "#DC8E68",
        // "Sirius Symboli" => true,
        "Smart Falcon" => "#FC67AD",
        // "Sounds of Earth" => true,
        "Special Week" => "#E877D2",
        // "Stay Gold" => true,
        // "Still in Love" => true,
        "Super Creek" => "#75BFDE",
        // "Sweep Tosho" => true,
        // "Symboli Kris S" => true,
        "Symboli Rudolf" => "#467F64",
        "T.M. Opera O" => "#FBB560",
        "Taiki Shuttle" => "#86CC48",
        "Tamamo Cross" => "#5C9EFD",
        // "Tanino Gimlet" => true,
        // "Tap Dance City" => true,
        "Tokai Teio" => "#587CE0",
        "Tosen Jordan" => "#5C71E5",
        // "Transcend" => true,
        // "Tsurumaru Tsuyoshi" => true,
        // "Twin Turbo" => true,
        "Vodka" => "#FEFF64",
        "Winning Ticket" => "#EF1D23",
        _ => "#000000",
    }
    .to_string()
}
